/*
** DON'T EDIT THIS FILE **
It's been generated by Zapatos, and is liable to be overwritten

Zapatos: https://jawj.github.io/zapatos/
Copyright (C) 2020 - 2022 George MacKerron
Released under the MIT licence: see LICENCE file
*/

declare module 'zapatos/schema' {

  import type * as db from 'zapatos/db';
  import type * as c from 'zapatos/custom';

  // got a type error on schemaVersionCanary below? update by running `npx zapatos`
  export interface schemaVersionCanary extends db.SchemaVersionCanary { version: 104 }


  /* === schema: public === */

  /* --- enums --- */

  export type category = 'Cultural' | 'Mixed' | 'Natural';
  export namespace every {
    export type category = ['Cultural', 'Mixed', 'Natural'];
  }
  export type category_short = 'C' | 'C/N' | 'N';
  export namespace every {
    export type category_short = ['C', 'C/N', 'N'];
  }

  /* --- tables --- */

  /**
   * **employees**
   * - Table in database
   */
  export namespace employees {
    export type Table = 'employees';
    export interface Selectable {
      /**
      * **employees.emp_no**
      * - `int4` in database
      * - Nullable, no default
      */
      emp_no: number | null;
      /**
      * **employees.first_name**
      * - `text` in database
      * - Nullable, no default
      */
      first_name: string | null;
      /**
      * **employees.last_name**
      * - `text` in database
      * - Nullable, no default
      */
      last_name: string | null;
    }
    export interface JSONSelectable {
      /**
      * **employees.emp_no**
      * - `int4` in database
      * - Nullable, no default
      */
      emp_no: number | null;
      /**
      * **employees.first_name**
      * - `text` in database
      * - Nullable, no default
      */
      first_name: string | null;
      /**
      * **employees.last_name**
      * - `text` in database
      * - Nullable, no default
      */
      last_name: string | null;
    }
    export interface Whereable {
      /**
      * **employees.emp_no**
      * - `int4` in database
      * - Nullable, no default
      */
      emp_no?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **employees.first_name**
      * - `text` in database
      * - Nullable, no default
      */
      first_name?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **employees.last_name**
      * - `text` in database
      * - Nullable, no default
      */
      last_name?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
    }
    export interface Insertable {
      /**
      * **employees.emp_no**
      * - `int4` in database
      * - Nullable, no default
      */
      emp_no?: number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment;
      /**
      * **employees.first_name**
      * - `text` in database
      * - Nullable, no default
      */
      first_name?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment;
      /**
      * **employees.last_name**
      * - `text` in database
      * - Nullable, no default
      */
      last_name?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment;
    }
    export interface Updatable {
      /**
      * **employees.emp_no**
      * - `int4` in database
      * - Nullable, no default
      */
      emp_no?: number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **employees.first_name**
      * - `text` in database
      * - Nullable, no default
      */
      first_name?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **employees.last_name**
      * - `text` in database
      * - Nullable, no default
      */
      last_name?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment>;
    }
    export type UniqueIndex = never;
    export type Column = keyof Selectable;
    export type OnlyCols<T extends readonly Column[]> = Pick<Selectable, T[number]>;
    export type SQLExpression = Table | db.ColumnNames<Updatable | (keyof Updatable)[]> | db.ColumnValues<Updatable> | Whereable | Column | db.ParentColumn | db.GenericSQLExpression;
    export type SQL = SQLExpression | SQLExpression[];
  }

  /**
   * **pokemon**
   * - Table in database
   */
  export namespace pokemon {
    export type Table = 'pokemon';
    export interface Selectable {
      /**
      * **pokemon.id**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      id: number;
      /**
      * **pokemon.name**
      * - `varchar` in database
      * - `NOT NULL`, no default
      */
      name: string;
      /**
      * **pokemon.type**
      * - `varchar` in database
      * - `NOT NULL`, no default
      */
      type: string;
    }
    export interface JSONSelectable {
      /**
      * **pokemon.id**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      id: number;
      /**
      * **pokemon.name**
      * - `varchar` in database
      * - `NOT NULL`, no default
      */
      name: string;
      /**
      * **pokemon.type**
      * - `varchar` in database
      * - `NOT NULL`, no default
      */
      type: string;
    }
    export interface Whereable {
      /**
      * **pokemon.id**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      id?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **pokemon.name**
      * - `varchar` in database
      * - `NOT NULL`, no default
      */
      name?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **pokemon.type**
      * - `varchar` in database
      * - `NOT NULL`, no default
      */
      type?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
    }
    export interface Insertable {
      /**
      * **pokemon.id**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      id: number | db.Parameter<number> | db.SQLFragment;
      /**
      * **pokemon.name**
      * - `varchar` in database
      * - `NOT NULL`, no default
      */
      name: string | db.Parameter<string> | db.SQLFragment;
      /**
      * **pokemon.type**
      * - `varchar` in database
      * - `NOT NULL`, no default
      */
      type: string | db.Parameter<string> | db.SQLFragment;
    }
    export interface Updatable {
      /**
      * **pokemon.id**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      id?: number | db.Parameter<number> | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment>;
      /**
      * **pokemon.name**
      * - `varchar` in database
      * - `NOT NULL`, no default
      */
      name?: string | db.Parameter<string> | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment>;
      /**
      * **pokemon.type**
      * - `varchar` in database
      * - `NOT NULL`, no default
      */
      type?: string | db.Parameter<string> | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment>;
    }
    export type UniqueIndex = 'pokemon_pkey';
    export type Column = keyof Selectable;
    export type OnlyCols<T extends readonly Column[]> = Pick<Selectable, T[number]>;
    export type SQLExpression = Table | db.ColumnNames<Updatable | (keyof Updatable)[]> | db.ColumnValues<Updatable> | Whereable | Column | db.ParentColumn | db.GenericSQLExpression;
    export type SQL = SQLExpression | SQLExpression[];
  }

  /**
   * **whc_sites_2021**
   * - Table in database
   */
  export namespace whc_sites_2021 {
    export type Table = 'whc_sites_2021';
    export interface Selectable {
      /**
      * **whc_sites_2021.unique_number**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      unique_number: number;
      /**
      * **whc_sites_2021.id_no**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      id_no: number;
      /**
      * **whc_sites_2021.rev_bis**
      * - `text` in database
      * - Nullable, no default
      */
      rev_bis: string | null;
      /**
      * **whc_sites_2021.name_en**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      name_en: string;
      /**
      * **whc_sites_2021.name_fr**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      name_fr: string;
      /**
      * **whc_sites_2021.short_description_en**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      short_description_en: string;
      /**
      * **whc_sites_2021.short_description_fr**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      short_description_fr: string;
      /**
      * **whc_sites_2021.justification_en**
      * - `text` in database
      * - Nullable, no default
      */
      justification_en: string | null;
      /**
      * **whc_sites_2021.justification_fr**
      * - `text` in database
      * - Nullable, no default
      */
      justification_fr: string | null;
      /**
      * **whc_sites_2021.date_inscribed**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      date_inscribed: number;
      /**
      * **whc_sites_2021.secondary_dates**
      * - `text` in database
      * - Nullable, no default
      */
      secondary_dates: string | null;
      /**
      * **whc_sites_2021.danger**
      * - `int4` in database
      * - Nullable, no default
      */
      danger: number | null;
      /**
      * **whc_sites_2021.date_end**
      * - `int4` in database
      * - Nullable, no default
      */
      date_end: number | null;
      /**
      * **whc_sites_2021.danger_list**
      * - `text` in database
      * - Nullable, no default
      */
      danger_list: string | null;
      /**
      * **whc_sites_2021.longitude**
      * - `float8` in database
      * - `NOT NULL`, no default
      */
      longitude: number;
      /**
      * **whc_sites_2021.latitude**
      * - `float8` in database
      * - `NOT NULL`, no default
      */
      latitude: number;
      /**
      * **whc_sites_2021.area_hectares**
      * - `float8` in database
      * - Nullable, no default
      */
      area_hectares: number | null;
      /**
      * **whc_sites_2021.c1**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      c1: number;
      /**
      * **whc_sites_2021.c2**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      c2: number;
      /**
      * **whc_sites_2021.c3**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      c3: number;
      /**
      * **whc_sites_2021.c4**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      c4: number;
      /**
      * **whc_sites_2021.c5**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      c5: number;
      /**
      * **whc_sites_2021.c6**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      c6: number;
      /**
      * **whc_sites_2021.n7**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      n7: number;
      /**
      * **whc_sites_2021.n8**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      n8: number;
      /**
      * **whc_sites_2021.n9**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      n9: number;
      /**
      * **whc_sites_2021.n10**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      n10: number;
      /**
      * **whc_sites_2021.criteria_txt**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      criteria_txt: string;
      /**
      * **whc_sites_2021.category**
      * - `category` in database
      * - `NOT NULL`, no default
      */
      category: category;
      /**
      * **whc_sites_2021.category_short**
      * - `category_short` in database
      * - `NOT NULL`, no default
      */
      category_short: category_short;
      /**
      * **whc_sites_2021.states_name_en**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      states_name_en: string;
      /**
      * **whc_sites_2021.states_name_fr**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      states_name_fr: string;
      /**
      * **whc_sites_2021.region_en**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      region_en: string;
      /**
      * **whc_sites_2021.region_fr**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      region_fr: string;
      /**
      * **whc_sites_2021.iso_code**
      * - `text` in database
      * - Nullable, no default
      */
      iso_code: string | null;
      /**
      * **whc_sites_2021.udnp_code**
      * - `text` in database
      * - Nullable, no default
      */
      udnp_code: string | null;
      /**
      * **whc_sites_2021.transboundary**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      transboundary: number;
      /**
      * **whc_sites_2021.location**
      * - `geography` in database
      * - Nullable, no default
      */
      location: c.PgGeography | null;
    }
    export interface JSONSelectable {
      /**
      * **whc_sites_2021.unique_number**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      unique_number: number;
      /**
      * **whc_sites_2021.id_no**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      id_no: number;
      /**
      * **whc_sites_2021.rev_bis**
      * - `text` in database
      * - Nullable, no default
      */
      rev_bis: string | null;
      /**
      * **whc_sites_2021.name_en**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      name_en: string;
      /**
      * **whc_sites_2021.name_fr**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      name_fr: string;
      /**
      * **whc_sites_2021.short_description_en**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      short_description_en: string;
      /**
      * **whc_sites_2021.short_description_fr**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      short_description_fr: string;
      /**
      * **whc_sites_2021.justification_en**
      * - `text` in database
      * - Nullable, no default
      */
      justification_en: string | null;
      /**
      * **whc_sites_2021.justification_fr**
      * - `text` in database
      * - Nullable, no default
      */
      justification_fr: string | null;
      /**
      * **whc_sites_2021.date_inscribed**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      date_inscribed: number;
      /**
      * **whc_sites_2021.secondary_dates**
      * - `text` in database
      * - Nullable, no default
      */
      secondary_dates: string | null;
      /**
      * **whc_sites_2021.danger**
      * - `int4` in database
      * - Nullable, no default
      */
      danger: number | null;
      /**
      * **whc_sites_2021.date_end**
      * - `int4` in database
      * - Nullable, no default
      */
      date_end: number | null;
      /**
      * **whc_sites_2021.danger_list**
      * - `text` in database
      * - Nullable, no default
      */
      danger_list: string | null;
      /**
      * **whc_sites_2021.longitude**
      * - `float8` in database
      * - `NOT NULL`, no default
      */
      longitude: number;
      /**
      * **whc_sites_2021.latitude**
      * - `float8` in database
      * - `NOT NULL`, no default
      */
      latitude: number;
      /**
      * **whc_sites_2021.area_hectares**
      * - `float8` in database
      * - Nullable, no default
      */
      area_hectares: number | null;
      /**
      * **whc_sites_2021.c1**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      c1: number;
      /**
      * **whc_sites_2021.c2**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      c2: number;
      /**
      * **whc_sites_2021.c3**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      c3: number;
      /**
      * **whc_sites_2021.c4**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      c4: number;
      /**
      * **whc_sites_2021.c5**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      c5: number;
      /**
      * **whc_sites_2021.c6**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      c6: number;
      /**
      * **whc_sites_2021.n7**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      n7: number;
      /**
      * **whc_sites_2021.n8**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      n8: number;
      /**
      * **whc_sites_2021.n9**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      n9: number;
      /**
      * **whc_sites_2021.n10**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      n10: number;
      /**
      * **whc_sites_2021.criteria_txt**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      criteria_txt: string;
      /**
      * **whc_sites_2021.category**
      * - `category` in database
      * - `NOT NULL`, no default
      */
      category: category;
      /**
      * **whc_sites_2021.category_short**
      * - `category_short` in database
      * - `NOT NULL`, no default
      */
      category_short: category_short;
      /**
      * **whc_sites_2021.states_name_en**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      states_name_en: string;
      /**
      * **whc_sites_2021.states_name_fr**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      states_name_fr: string;
      /**
      * **whc_sites_2021.region_en**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      region_en: string;
      /**
      * **whc_sites_2021.region_fr**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      region_fr: string;
      /**
      * **whc_sites_2021.iso_code**
      * - `text` in database
      * - Nullable, no default
      */
      iso_code: string | null;
      /**
      * **whc_sites_2021.udnp_code**
      * - `text` in database
      * - Nullable, no default
      */
      udnp_code: string | null;
      /**
      * **whc_sites_2021.transboundary**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      transboundary: number;
      /**
      * **whc_sites_2021.location**
      * - `geography` in database
      * - Nullable, no default
      */
      location: c.PgGeography | null;
    }
    export interface Whereable {
      /**
      * **whc_sites_2021.unique_number**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      unique_number?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **whc_sites_2021.id_no**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      id_no?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **whc_sites_2021.rev_bis**
      * - `text` in database
      * - Nullable, no default
      */
      rev_bis?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **whc_sites_2021.name_en**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      name_en?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **whc_sites_2021.name_fr**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      name_fr?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **whc_sites_2021.short_description_en**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      short_description_en?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **whc_sites_2021.short_description_fr**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      short_description_fr?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **whc_sites_2021.justification_en**
      * - `text` in database
      * - Nullable, no default
      */
      justification_en?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **whc_sites_2021.justification_fr**
      * - `text` in database
      * - Nullable, no default
      */
      justification_fr?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **whc_sites_2021.date_inscribed**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      date_inscribed?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **whc_sites_2021.secondary_dates**
      * - `text` in database
      * - Nullable, no default
      */
      secondary_dates?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **whc_sites_2021.danger**
      * - `int4` in database
      * - Nullable, no default
      */
      danger?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **whc_sites_2021.date_end**
      * - `int4` in database
      * - Nullable, no default
      */
      date_end?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **whc_sites_2021.danger_list**
      * - `text` in database
      * - Nullable, no default
      */
      danger_list?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **whc_sites_2021.longitude**
      * - `float8` in database
      * - `NOT NULL`, no default
      */
      longitude?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **whc_sites_2021.latitude**
      * - `float8` in database
      * - `NOT NULL`, no default
      */
      latitude?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **whc_sites_2021.area_hectares**
      * - `float8` in database
      * - Nullable, no default
      */
      area_hectares?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **whc_sites_2021.c1**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      c1?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **whc_sites_2021.c2**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      c2?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **whc_sites_2021.c3**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      c3?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **whc_sites_2021.c4**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      c4?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **whc_sites_2021.c5**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      c5?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **whc_sites_2021.c6**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      c6?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **whc_sites_2021.n7**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      n7?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **whc_sites_2021.n8**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      n8?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **whc_sites_2021.n9**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      n9?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **whc_sites_2021.n10**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      n10?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **whc_sites_2021.criteria_txt**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      criteria_txt?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **whc_sites_2021.category**
      * - `category` in database
      * - `NOT NULL`, no default
      */
      category?: category | db.Parameter<category> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, category | db.Parameter<category> | db.SQLFragment | db.ParentColumn>;
      /**
      * **whc_sites_2021.category_short**
      * - `category_short` in database
      * - `NOT NULL`, no default
      */
      category_short?: category_short | db.Parameter<category_short> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, category_short | db.Parameter<category_short> | db.SQLFragment | db.ParentColumn>;
      /**
      * **whc_sites_2021.states_name_en**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      states_name_en?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **whc_sites_2021.states_name_fr**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      states_name_fr?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **whc_sites_2021.region_en**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      region_en?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **whc_sites_2021.region_fr**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      region_fr?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **whc_sites_2021.iso_code**
      * - `text` in database
      * - Nullable, no default
      */
      iso_code?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **whc_sites_2021.udnp_code**
      * - `text` in database
      * - Nullable, no default
      */
      udnp_code?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **whc_sites_2021.transboundary**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      transboundary?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **whc_sites_2021.location**
      * - `geography` in database
      * - Nullable, no default
      */
      location?: c.PgGeography | db.Parameter<c.PgGeography> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, c.PgGeography | db.Parameter<c.PgGeography> | db.SQLFragment | db.ParentColumn>;
    }
    export interface Insertable {
      /**
      * **whc_sites_2021.unique_number**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      unique_number: number | db.Parameter<number> | db.SQLFragment;
      /**
      * **whc_sites_2021.id_no**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      id_no: number | db.Parameter<number> | db.SQLFragment;
      /**
      * **whc_sites_2021.rev_bis**
      * - `text` in database
      * - Nullable, no default
      */
      rev_bis?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment;
      /**
      * **whc_sites_2021.name_en**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      name_en: string | db.Parameter<string> | db.SQLFragment;
      /**
      * **whc_sites_2021.name_fr**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      name_fr: string | db.Parameter<string> | db.SQLFragment;
      /**
      * **whc_sites_2021.short_description_en**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      short_description_en: string | db.Parameter<string> | db.SQLFragment;
      /**
      * **whc_sites_2021.short_description_fr**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      short_description_fr: string | db.Parameter<string> | db.SQLFragment;
      /**
      * **whc_sites_2021.justification_en**
      * - `text` in database
      * - Nullable, no default
      */
      justification_en?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment;
      /**
      * **whc_sites_2021.justification_fr**
      * - `text` in database
      * - Nullable, no default
      */
      justification_fr?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment;
      /**
      * **whc_sites_2021.date_inscribed**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      date_inscribed: number | db.Parameter<number> | db.SQLFragment;
      /**
      * **whc_sites_2021.secondary_dates**
      * - `text` in database
      * - Nullable, no default
      */
      secondary_dates?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment;
      /**
      * **whc_sites_2021.danger**
      * - `int4` in database
      * - Nullable, no default
      */
      danger?: number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment;
      /**
      * **whc_sites_2021.date_end**
      * - `int4` in database
      * - Nullable, no default
      */
      date_end?: number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment;
      /**
      * **whc_sites_2021.danger_list**
      * - `text` in database
      * - Nullable, no default
      */
      danger_list?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment;
      /**
      * **whc_sites_2021.longitude**
      * - `float8` in database
      * - `NOT NULL`, no default
      */
      longitude: number | db.Parameter<number> | db.SQLFragment;
      /**
      * **whc_sites_2021.latitude**
      * - `float8` in database
      * - `NOT NULL`, no default
      */
      latitude: number | db.Parameter<number> | db.SQLFragment;
      /**
      * **whc_sites_2021.area_hectares**
      * - `float8` in database
      * - Nullable, no default
      */
      area_hectares?: number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment;
      /**
      * **whc_sites_2021.c1**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      c1: number | db.Parameter<number> | db.SQLFragment;
      /**
      * **whc_sites_2021.c2**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      c2: number | db.Parameter<number> | db.SQLFragment;
      /**
      * **whc_sites_2021.c3**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      c3: number | db.Parameter<number> | db.SQLFragment;
      /**
      * **whc_sites_2021.c4**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      c4: number | db.Parameter<number> | db.SQLFragment;
      /**
      * **whc_sites_2021.c5**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      c5: number | db.Parameter<number> | db.SQLFragment;
      /**
      * **whc_sites_2021.c6**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      c6: number | db.Parameter<number> | db.SQLFragment;
      /**
      * **whc_sites_2021.n7**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      n7: number | db.Parameter<number> | db.SQLFragment;
      /**
      * **whc_sites_2021.n8**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      n8: number | db.Parameter<number> | db.SQLFragment;
      /**
      * **whc_sites_2021.n9**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      n9: number | db.Parameter<number> | db.SQLFragment;
      /**
      * **whc_sites_2021.n10**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      n10: number | db.Parameter<number> | db.SQLFragment;
      /**
      * **whc_sites_2021.criteria_txt**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      criteria_txt: string | db.Parameter<string> | db.SQLFragment;
      /**
      * **whc_sites_2021.category**
      * - `category` in database
      * - `NOT NULL`, no default
      */
      category: category | db.Parameter<category> | db.SQLFragment;
      /**
      * **whc_sites_2021.category_short**
      * - `category_short` in database
      * - `NOT NULL`, no default
      */
      category_short: category_short | db.Parameter<category_short> | db.SQLFragment;
      /**
      * **whc_sites_2021.states_name_en**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      states_name_en: string | db.Parameter<string> | db.SQLFragment;
      /**
      * **whc_sites_2021.states_name_fr**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      states_name_fr: string | db.Parameter<string> | db.SQLFragment;
      /**
      * **whc_sites_2021.region_en**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      region_en: string | db.Parameter<string> | db.SQLFragment;
      /**
      * **whc_sites_2021.region_fr**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      region_fr: string | db.Parameter<string> | db.SQLFragment;
      /**
      * **whc_sites_2021.iso_code**
      * - `text` in database
      * - Nullable, no default
      */
      iso_code?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment;
      /**
      * **whc_sites_2021.udnp_code**
      * - `text` in database
      * - Nullable, no default
      */
      udnp_code?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment;
      /**
      * **whc_sites_2021.transboundary**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      transboundary: number | db.Parameter<number> | db.SQLFragment;
      /**
      * **whc_sites_2021.location**
      * - `geography` in database
      * - Nullable, no default
      */
      location?: c.PgGeography | db.Parameter<c.PgGeography> | null | db.DefaultType | db.SQLFragment;
    }
    export interface Updatable {
      /**
      * **whc_sites_2021.unique_number**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      unique_number?: number | db.Parameter<number> | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment>;
      /**
      * **whc_sites_2021.id_no**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      id_no?: number | db.Parameter<number> | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment>;
      /**
      * **whc_sites_2021.rev_bis**
      * - `text` in database
      * - Nullable, no default
      */
      rev_bis?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **whc_sites_2021.name_en**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      name_en?: string | db.Parameter<string> | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment>;
      /**
      * **whc_sites_2021.name_fr**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      name_fr?: string | db.Parameter<string> | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment>;
      /**
      * **whc_sites_2021.short_description_en**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      short_description_en?: string | db.Parameter<string> | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment>;
      /**
      * **whc_sites_2021.short_description_fr**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      short_description_fr?: string | db.Parameter<string> | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment>;
      /**
      * **whc_sites_2021.justification_en**
      * - `text` in database
      * - Nullable, no default
      */
      justification_en?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **whc_sites_2021.justification_fr**
      * - `text` in database
      * - Nullable, no default
      */
      justification_fr?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **whc_sites_2021.date_inscribed**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      date_inscribed?: number | db.Parameter<number> | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment>;
      /**
      * **whc_sites_2021.secondary_dates**
      * - `text` in database
      * - Nullable, no default
      */
      secondary_dates?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **whc_sites_2021.danger**
      * - `int4` in database
      * - Nullable, no default
      */
      danger?: number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **whc_sites_2021.date_end**
      * - `int4` in database
      * - Nullable, no default
      */
      date_end?: number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **whc_sites_2021.danger_list**
      * - `text` in database
      * - Nullable, no default
      */
      danger_list?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **whc_sites_2021.longitude**
      * - `float8` in database
      * - `NOT NULL`, no default
      */
      longitude?: number | db.Parameter<number> | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment>;
      /**
      * **whc_sites_2021.latitude**
      * - `float8` in database
      * - `NOT NULL`, no default
      */
      latitude?: number | db.Parameter<number> | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment>;
      /**
      * **whc_sites_2021.area_hectares**
      * - `float8` in database
      * - Nullable, no default
      */
      area_hectares?: number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **whc_sites_2021.c1**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      c1?: number | db.Parameter<number> | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment>;
      /**
      * **whc_sites_2021.c2**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      c2?: number | db.Parameter<number> | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment>;
      /**
      * **whc_sites_2021.c3**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      c3?: number | db.Parameter<number> | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment>;
      /**
      * **whc_sites_2021.c4**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      c4?: number | db.Parameter<number> | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment>;
      /**
      * **whc_sites_2021.c5**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      c5?: number | db.Parameter<number> | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment>;
      /**
      * **whc_sites_2021.c6**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      c6?: number | db.Parameter<number> | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment>;
      /**
      * **whc_sites_2021.n7**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      n7?: number | db.Parameter<number> | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment>;
      /**
      * **whc_sites_2021.n8**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      n8?: number | db.Parameter<number> | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment>;
      /**
      * **whc_sites_2021.n9**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      n9?: number | db.Parameter<number> | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment>;
      /**
      * **whc_sites_2021.n10**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      n10?: number | db.Parameter<number> | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment>;
      /**
      * **whc_sites_2021.criteria_txt**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      criteria_txt?: string | db.Parameter<string> | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment>;
      /**
      * **whc_sites_2021.category**
      * - `category` in database
      * - `NOT NULL`, no default
      */
      category?: category | db.Parameter<category> | db.SQLFragment | db.SQLFragment<any, category | db.Parameter<category> | db.SQLFragment>;
      /**
      * **whc_sites_2021.category_short**
      * - `category_short` in database
      * - `NOT NULL`, no default
      */
      category_short?: category_short | db.Parameter<category_short> | db.SQLFragment | db.SQLFragment<any, category_short | db.Parameter<category_short> | db.SQLFragment>;
      /**
      * **whc_sites_2021.states_name_en**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      states_name_en?: string | db.Parameter<string> | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment>;
      /**
      * **whc_sites_2021.states_name_fr**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      states_name_fr?: string | db.Parameter<string> | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment>;
      /**
      * **whc_sites_2021.region_en**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      region_en?: string | db.Parameter<string> | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment>;
      /**
      * **whc_sites_2021.region_fr**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      region_fr?: string | db.Parameter<string> | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment>;
      /**
      * **whc_sites_2021.iso_code**
      * - `text` in database
      * - Nullable, no default
      */
      iso_code?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **whc_sites_2021.udnp_code**
      * - `text` in database
      * - Nullable, no default
      */
      udnp_code?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **whc_sites_2021.transboundary**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      transboundary?: number | db.Parameter<number> | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment>;
      /**
      * **whc_sites_2021.location**
      * - `geography` in database
      * - Nullable, no default
      */
      location?: c.PgGeography | db.Parameter<c.PgGeography> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, c.PgGeography | db.Parameter<c.PgGeography> | null | db.DefaultType | db.SQLFragment>;
    }
    export type UniqueIndex = 'whc_sites_2021_pkey';
    export type Column = keyof Selectable;
    export type OnlyCols<T extends readonly Column[]> = Pick<Selectable, T[number]>;
    export type SQLExpression = Table | db.ColumnNames<Updatable | (keyof Updatable)[]> | db.ColumnValues<Updatable> | Whereable | Column | db.ParentColumn | db.GenericSQLExpression;
    export type SQL = SQLExpression | SQLExpression[];
  }

  /* --- aggregate types --- */

  export namespace public {  
    export type Table = employees.Table | pokemon.Table | whc_sites_2021.Table;
    export type Selectable = employees.Selectable | pokemon.Selectable | whc_sites_2021.Selectable;
    export type JSONSelectable = employees.JSONSelectable | pokemon.JSONSelectable | whc_sites_2021.JSONSelectable;
    export type Whereable = employees.Whereable | pokemon.Whereable | whc_sites_2021.Whereable;
    export type Insertable = employees.Insertable | pokemon.Insertable | whc_sites_2021.Insertable;
    export type Updatable = employees.Updatable | pokemon.Updatable | whc_sites_2021.Updatable;
    export type UniqueIndex = employees.UniqueIndex | pokemon.UniqueIndex | whc_sites_2021.UniqueIndex;
    export type Column = employees.Column | pokemon.Column | whc_sites_2021.Column;
  
    export type AllBaseTables = [employees.Table, pokemon.Table, whc_sites_2021.Table];
    export type AllForeignTables = [];
    export type AllViews = [];
    export type AllMaterializedViews = [];
    export type AllTablesAndViews = [employees.Table, pokemon.Table, whc_sites_2021.Table];
  }



  /* === global aggregate types === */

  export type Schema = 'public';
  export type Table = public.Table;
  export type Selectable = public.Selectable;
  export type JSONSelectable = public.JSONSelectable;
  export type Whereable = public.Whereable;
  export type Insertable = public.Insertable;
  export type Updatable = public.Updatable;
  export type UniqueIndex = public.UniqueIndex;
  export type Column = public.Column;

  export type AllSchemas = ['public'];
  export type AllBaseTables = [...public.AllBaseTables];
  export type AllForeignTables = [...public.AllForeignTables];
  export type AllViews = [...public.AllViews];
  export type AllMaterializedViews = [...public.AllMaterializedViews];
  export type AllTablesAndViews = [...public.AllTablesAndViews];


  /* === lookups === */

  export type SelectableForTable<T extends Table> = {
    "employees": employees.Selectable;
    "pokemon": pokemon.Selectable;
    "whc_sites_2021": whc_sites_2021.Selectable;
  }[T];

  export type JSONSelectableForTable<T extends Table> = {
    "employees": employees.JSONSelectable;
    "pokemon": pokemon.JSONSelectable;
    "whc_sites_2021": whc_sites_2021.JSONSelectable;
  }[T];

  export type WhereableForTable<T extends Table> = {
    "employees": employees.Whereable;
    "pokemon": pokemon.Whereable;
    "whc_sites_2021": whc_sites_2021.Whereable;
  }[T];

  export type InsertableForTable<T extends Table> = {
    "employees": employees.Insertable;
    "pokemon": pokemon.Insertable;
    "whc_sites_2021": whc_sites_2021.Insertable;
  }[T];

  export type UpdatableForTable<T extends Table> = {
    "employees": employees.Updatable;
    "pokemon": pokemon.Updatable;
    "whc_sites_2021": whc_sites_2021.Updatable;
  }[T];

  export type UniqueIndexForTable<T extends Table> = {
    "employees": employees.UniqueIndex;
    "pokemon": pokemon.UniqueIndex;
    "whc_sites_2021": whc_sites_2021.UniqueIndex;
  }[T];

  export type ColumnForTable<T extends Table> = {
    "employees": employees.Column;
    "pokemon": pokemon.Column;
    "whc_sites_2021": whc_sites_2021.Column;
  }[T];

  export type SQLForTable<T extends Table> = {
    "employees": employees.SQL;
    "pokemon": pokemon.SQL;
    "whc_sites_2021": whc_sites_2021.SQL;
  }[T];

}
